version: "3"

networks:
  default:

volumes:
  database:

services:
  database:
    image: diegmonti/test_db
    volumes:
      - database:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    environment: 
      DB_HOST: database
      DB_PASSWORD: 1234
      DB_USERNAME: postgres
      DB_PORT: 5432
      DB_DATABASE: postgres
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: efraim/acmehr
    ports:
      - 5000:5000
    depends_on:
      database:
          condition: service_healthy
    networks:
      - default
